variables:
  GIT_DEPTH: '100'
  
stages:
  - lint
  - test

lint:
  stage: lint
  image: node:latest
  script:
    - npm install
    - npm run lint

prettier:
  stage: lint
  image: node:latest
  script:
    - npm install
    - npm run prettier

test:
  stage: test
  image: node:latest
  script:
    - npm install
    - npm run test:client
    - npm run test:server
